# fly.toml app configuration file generated for zen-demo-java on 2025-01-28T15:42:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zen-demo-java-danger'
primary_region = 'ams'

[[vm]]
  memory = '1024mb'
  cpu_kind = 'performance'
  cpus = 1

[env]
AIKIDO_DISABLE = 'true'
